export const ROOT_URL = "http://54.67.94.219:5000/api";

export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";

export const DASHBOARD_TASKS = "DASHBOARD_TASKS";
export const DASHBOARD_CURRENT_PAGE_TASKS = "DASHBOARD_CURRENT_PAGE_TASKS";

export const GET_PROFILE = "GET_PROFILE";
export const SAVE_PROFILE = "SAVE_PROFILE";
export const DEACTIVATE_PROFILE = "DEACTIVATE_PROFILE";

export const SAVE_TASK = "SAVE_TASK";
export const GET_TASK = "GET_TASK";

export const GET_ALL_TASKS = "GET_ALL_TASKS";

export const EDIT_TASK = "EDIT_TASK";
export const APPLY_TASK = "APPLY_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const SELECTED_CANDIDATES = "SELECTED_CANDIDATES";
export const GET_SELECTED_CANDIDATES = "GET_SELECTED_CANDIDATES";
export const GET_SPONSOR_PROFILE = "GET_SPONSOR_PROFILE";
export const MARK_COMPLETE = "MARK_COMPLETE";

export const SEARCH_TASKS = "SEARCH_TASKS";
export const SEARCH_PEOPLE = "SEARCH_PEOPLE";
export const SEARCH_PEOPLE_SORTED_AZ = "SEARCH_PEOPLE_SORTED_AZ";
export const SEARCH_PEOPLE_SORTED_ZA = "SEARCH_PEOPLE_SORTED_ZA";
export const SORT_PEOPLE_RATINGS_LOW_TO_HIGH =
  "SORT_PEOPLE_RATINGS_LOW_TO_HIGH";
export const SORT_PEOPLE_RATINGS_HIGH_TO_LOW =
  "SORT_PEOPLE_RATINGS_HIGH_TO_LOW";

export const FETCH_CONVERSATIONS = "FETCH_CONVERSATIONS";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const MARK_READ = "MARK_READ";
export const FETCH_ALL_USERS_INBOX = "FETCH_ALL_USERS_INBOX";

export const GET_INFLUENCER_RATINGS = "GET_INFLUENCER_RATINGS";
export const GET_SPONSOR_RATINGS = "GET_SPONSOR_RATINGS";
export const SORT_RATINGS_LOW_TO_HIGH = "SORT_RATINGS_LOW_TO_HIGH";
export const SORT_RATINGS_HIGH_TO_LOW = "SORT_RATINGS_HIGH_TO_LOW";

export const SORT_INCOME_LOW_TO_HIGH = "SORT_INCOME_LOW_TO_HIGH";
export const SORT_INCOME_HIGH_TO_LOW = "SORT_INCOME_HIGH_TO_LOW";

export const MOST_RECENT_TASKS = "MOST_RECENT_TASKS";

export const UNRATED_INFLUENCERS = "UNRATED_INFLUENCERS";
export const ADD_RATING = "ADD_RATING";
export const MARK_DASHBOARD_TASK_COMPLETE = "MARK_DASHBOARD_TASK_COMPLETE";
export const CANCEL_DASHBOARD_TASK = "CANCEL_DASHBOARD_TASK";

export const PENDING_TASKS = "PENDING_TASKS";
export const INPROGRESS_TASKS = "INPROGRESS_TASKS";

export const RECENTLY_POSTED_TASKS = "RECENTLY_POSTED_TASKS";

export const MY_ACTIVE_TASKS = "MY_ACTIVE_TASKS";

export const RECOMMENDED_TASKS = "RECOMMENDED_TASKS";

//Analytics

export const INFLUENCER_RATINGS_BY_CATEGORY = "INFLUENCER_RATINGS_BY_CATEGORY";
export const INFLUENCER_EARNINGS_BY_CATEGORY =
  "INFLUENCER_EARNINGS_BY_CATEGORY";
export const INFLUENCER_TASKS_COMPLETED_BY_CATEGORY =
  "INFLUENCER_TASKS_COMPLETED_BY_CATEGORY";

export const SPONSOR_PAYMENT_BY_CATEGORY = "SPONSOR_PAYMENT_BY_CATEGORY";
export const SPONSOR_COMPLETED_TASKS_BY_CATEGORY =
  "SPONSOR_COMPLETED_TASKS_BY_CATEGORY";
export const SPONSOR_ALL_TASKS_BY_CATEGORY = "SPONSOR_ALL_TASKS_BY_CATEGORY";
