export const ROOT_URL = "http://localhost:5000/api";

export const LOGIN_USER = 'LOGIN_USER';

export const DASHBOARD_TASKS = 'DASHBOARD_TASKS';
export const DASHBOARD_CURRENT_PAGE_TASKS = 'DASHBOARD_CURRENT_PAGE_TASKS';

export const GET_PROFILE = "GET_PROFILE";
export const SAVE_PROFILE = "SAVE_PROFILE";

export const SAVE_TASK = "SAVE_TASK";

export const FETCH_CONVERSATIONS = 'FETCH_CONVERSATIONS'
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const MARK_READ = 'MARK_READ'
export const FETCH_ALL_USERS_INBOX = 'FETCH_ALL_USERS_INBOX'

export const GET_INFLUENCER_RATINGS = "GET_INFLUENCER_RATINGS";
export const GET_SPONSOR_RATINGS = "GET_SPONSOR_RATINGS";